### ISSUE TITLE
"Dark theme issue" Issue tracker

### ISSUE THREAD

**Issue by joebayles** [Esri/military-tools-for-arcgis#90]
As there are probably going to be several issues related to the new dark theme in ArcGIS Pro 1.4, creating a list of issues for reference.

**Military Tools for ArcGIS**
- [ ] https://github.com/Esri/military-tools-for-arcgis/issues/66 (Drop-down menus)
- [ ] https://github.com/Esri/military-tools-for-arcgis/issues/79 (Drop-down menus)
- [ ] https://github.com/Esri/military-tools-for-arcgis/issues/88 (Text boxes)
- [ ] https://github.com/Esri/military-tools-for-arcgis/issues/89 (Radial buttons)

**Distance and Direction**
- [ ] https://github.com/Esri/distance-direction-addin-dotnet/issues/233 (Drop-downs and Radials)

**Coordinate Conversion**
- [ ] https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/238 (Drop-down menus)

FYI @Esri/arcgis-defense-solutions

**Comment by joebayles** [comment]
To be clear, as of the 10 January 0900 build, Distance and Direction is _basically_ fixed, but Coordinate Conversion, Military Symbol Editor, and Visibility still have issues.

**Comment by joebayles** [comment]
Those interested in fixing these might look at the fixes @pHill5136 did with https://github.com/Esri/distance-direction-addin-dotnet/issues/233, because 👍 .

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/military-tools-pro-single-add-in#12
